### ISSUE TITLE
Only one mention of girth

### ISSUE THREAD

**Issue by refazi** [PLEBNET/wiki#3]
MORE GIRTH!!

**Comment by mh-ash** [comment]
G I R T H

**Comment by derekmiller** [comment]
![](https://media.giphy.com/media/WOkuT1LgiY41Fr1Me8/giphy-downsized.gif)

**Comment by refazi** [comment]
Great job, @phjlljp the last thing we need to cover is to point girth.plebnet.com to redirect to https://amboss.space/r/52ab78
